development:
 adapter: postgresql
 database: blog_development
 host: localhost

test:
 adapter: postgresql
 database: blog_test
 host: localhost

production:
 adapter: postgresql
 database: blog_production
 username: <%= ENV["DATABASE_USERNAME"] %>
 password: <%= ENV["DATABASE_PASSWORD"] %>